force-app/main/default/objects/Account/fields/Account_Activation_Summary__c.field-meta.xml
<CustomField>
    <fullName>Account_Activation_Summary__c</fullName>
    <description>It represents the brief description about Account Activation</description>
    <label>Account Activation Summary</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field represents the whether account is active or inactive</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AccountTriggerHandlerTest.cls
@IsTest
public class AccountTriggerHandlerTest {
    @IsTest
    static void testHandleAfterInsertOrUpdate() {       

        user u =[select id,name from user where id='0055i00000AklgE'];
        system.runAs(u){
        //create account with the required fields
        Account ac= new Account();
        ac.Name='test';
        ac.Active__c=TRUE;
        ac.Account_Activation_Summary__c='TESTING';
        ac.Type='Customer';
        Test.startTest();
        insert ac;     
        //create default contact after account creation
        contact ct= new contact();
        ct.AccountId=ac.id;
        ct.FirstName='TEST12';
        ct.LastName='test21';       
        insert ct;
        Test.stopTest();
        
    }
    }
}