force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field represents the whether account is active or inactive</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/DefaultContact__c.field-meta.xml
<CustomField>
    <fullName>DefaultContact__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field represents whenever account will create if the type as customer and active is checked then automatically default contact will create</description>
    <label>DefaultContact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AccountTriggerHandler.cls
public class AccountTriggerHandler {
    public static void handleAfterInsertUpdate(List<Account> accounts, Map<Id, Account> oldMap) {
        // Create a list to store new Contact records
       List<Contact> newContacts = new List<Contact>();
        
        for (Account acc : accounts) {
            if (acc.Active__c && acc.Type == 'Customer') {
                // Check if a default contact already exists
                Boolean defaultContactExists = [SELECT COUNT() FROM Contact WHERE AccountId = :acc.Id LIMIT 1] > 0;

                // Create a default customer contact if one does not exist
                if (!defaultContactExists) {
                    Contact newContact = new Contact();
                    newContact.FirstName = acc.Name;
                    newContact.DefaultContact__c = true;
                    newContact.LastName = 'Customer Representative';
                    newContact.Email = acc.Company_Email__c;
                    newContact.Phone = acc.Phone;
                    newContact.AccountId = acc.Id;

                    newContacts.add(newContact);
                }
            }
        }

        // Insert new contacts
        if (!newContacts.isEmpty()) {
            insert newContacts;
        }
    }
}